AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Documentation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Max: 60

Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 400

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/ParameterLists:
  Max: 8
